spring:
  application:
    name: api-notification

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: receipt_consumer
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false

server:
  port: 8084